variable "client_id" {
  description = "Contabo account ID."
  type = string
}
variable "client_secret" {
  description = "Contabo account secret."
  type = string
}
variable "api_user" {
  description = "Contabo account e-mail."
  type = string
}
variable "api_password" {
  description = "Contabo API password from API panel."
  type = string
}
variable "access_token" {
  description = "Uniq access token generated by Contabo CLI."
  type = string
}
